version: "3"
services:
  api:
    image: pedrotti/python:flask
    container_name: python-api
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    environment:
      # DB_CONNECTION_URL: 'mysql+mysqlconnector://root:root@dbhost/app'
      DB_DIALECT: 'mysql+mysqlconnector'
      DB_HOST: 'dbhost'
      DB_PORT: '3306'
      DB_USERNAME: 'root'
      DB_PASSWORD: 'root'
      DB_NAME: 'app'
      SECRET_KEY: '????????????????????????????????????????????????????????????????'
      JWT_SECRET: '????????????????????????????????????????????????????????????????'
    links:
      - db:dbhost
    network_mode: bridge
    command: python -m flask run --debug --host=0.0.0.0
  db:
    image: mysql:5.7
    container_name: python-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    ports:
      - 3306:3306
    network_mode: bridge